name: xWarp
version: 3.0.0 b0
main: me.taylorkelly.mywarp.MyWarp
description: Implementation to create warp points!
authors:
  - 'xZise'
  - 'tkelly'
commands:
  warp:
    description: Warp commands
    usage: /<command> help - Displays the help for all warp commands.
    aliases: [xwarp, w]
  wpa:
    description: Warp protection area handling commands.
    usage: /<command> help - Displays the help for all wpa commands.
    aliases: [xwpa]
  go:
    description: Warps you to the saved location.
    usage: /<command> [to] <warpname> [owner] [warped player]
