name: xWarp
version: 2.7.5-timers
main: me.taylorkelly.mywarp.MyWarp
description: Implementation to create warp points!
authors:
  - 'xZise'
  - 'tkelly'
commands:
  warp:
    description: Warp commands
    usage: /<command> help - Displays the help for xWarp
    aliases: [xwarp, w]
